services:
  app:
    build: .
    container_name: dididcrawler-app
    ports:
      - "8080:80"
    volumes:
      - ./storage:/var/www/html/storage
    restart: unless-stopped

  # Optional: Local MySQL for testing (comment out if using external DB)
  # mysql:
  #   image: mysql:8.0
  #   container_name: dididcrawler-mysql-local
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_DATABASE: dididcrawler
  #     MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  #     MYSQL_ROOT_PASSWORD: ""
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   command: --default-authentication-plugin=mysql_native_password

# volumes:
#   mysql_data: