services:
  app:
    build: .
    container_name: dididcrawler-app
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: dididcrawler-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: dididcrawler
      MYSQL_ROOT_PASSWORD: AlphA2112
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  traefik:
    image: traefik:v2.10
    container_name: dididcrawler-traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

volumes:
  mysql_data: