# nixpacks.toml

[phases.setup]
nixPkgs = ["...", "python311Packages.supervisor"]

[phases.build]
# Prepare supervisor configs and start script, and run default build cmds
cmds = [
  "php artisan storage:link",
  "mkdir -p /etc/supervisor/conf.d/",
  "cp /assets/laravel-worker.conf /etc/supervisor/conf.d/",
  "cp /assets/supervisord.conf /etc/supervisord.conf",
  "chmod +x /assets/start.sh",
  "..."  # ensures default provider build steps are included
]

[start]
# Launch start script for full stack
cmd = "/assets/start.sh"

[staticAssets]
"start.sh" = '''
#!/bin/bash
# Generate nginx config
node /assets/scripts/prestart.mjs /assets/nginx.template.conf /etc/nginx.conf

# Start PHP-FPM
php-fpm -y /assets/php-fpm.conf

# Start Supervisor to manage queue workers
supervisord -c /etc/supervisord.conf

# Start Nginx
nginx -c /etc/nginx.conf
'''

"supervisord.conf" = '''
[unix_http_server]
file=/assets/supervisor.sock

[supervisord]
logfile=/var/log/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/assets/supervisord.pid
nodaemon=false

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[include]
files = /etc/supervisor/conf.d/*.conf
'''

"laravel-worker.conf" = '''
[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /app/artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=8
startsecs=0
stopwaitsecs=3600
stdout_logfile=/var/log/laravel-worker.log
stderr_logfile=/var/log/laravel-worker.log
'''

"php-fpm.conf" = '''
[www]
listen = 127.0.0.1:9000
user = www-data
group = www-data
listen.owner = www-data
listen.group = www-data
pm = dynamic
pm.max_children = 50
pm.min_spare_servers = 4
pm.max_spare_servers = 32
pm.start_servers = 18
clear_env = no
'''

"nginx.template.conf" = '''
user www-data www-data;
worker_processes auto;
daemon off;

events {
    worker_connections 1024;
}

http {
    include       $!{nginx}/conf/mime.types;
    default_type  application/octet-stream;
    sendfile       on;
    keepalive_timeout 65;
    index index.php index.html;
    client_max_body_size 35M;

    server {
        listen 80;
        server_name localhost;

        root /app/public;
        try_files $uri $uri/ /index.php?$query_string;

        location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            include $!{nginx}/conf/fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            fastcgi_param PHP_VALUE "upload_max_filesize=35M\npost_max_size=35M";
        }

        location ~ /\.(?!well-known).* {
            deny all;
        }
    }
}
'''
